# pages/3_Gain_Pain_Analysis.py
#
# MODULE 3 — Gain-Pain Analysis.
#   Part 1 (problem selection: dropdown, cards, layout) — Friend's Project,
#           unchanged.
#   Part 2 (AI generated questions, gain/pain computation, priority
#           calculation, charts, recommendations) — My Project, formulas
#           and prompts unchanged.
#
# New flow per merge spec: after selecting a problem, the user explicitly
# chooses "Ask Clarifying Questions" or "Run Directly" (instead of always
# being forced through the clarifying-questions step). After results are
# shown, a new "Satisfied with Analysis?" prompt offers Yes / Request
# Expert Review, the latter handing off to the new Expert Advice page.

import streamlit as st
import json
import pandas as pd
from datetime import datetime

from config.constants import (GAIN_DIMENSIONS, PAIN_DIMENSIONS, PRIORITY_BANDS,
                              M3_SCORING_BASIS, M3_PRIORITY_FORMULA_HTML,
                              M3_AVG_GAINS_FORMULA_HTML, M3_AVG_PAINS_FORMULA_HTML)
from database.problem_repository import get_problems
from database.db import db_get_problem, db_load_assessments, db_save_gainpain, db_update_status, db_load_gainpain
from llm.gain_pain_logic import call_m3_ai, call_smart_questions_ai

from ui.theme import apply_theme
from ui.sidebar import render_sidebar
from ui.navbar import render_navbar, render_breadcrumb, render_subtabs

st.set_page_config(page_title="AI Governance Platform", page_icon="🤖",
                    layout="wide", initial_sidebar_state="expanded")

apply_theme()
render_sidebar("m3")
render_navbar("m3")
render_breadcrumb("Problem Selection", "Assessment")
render_subtabs(
    [("📊 Feasibility Assessment", "pages/2_Feasibility_Assessment.py"),
     ("⚖️ Gain-Pain Analysis", "pages/3_Gain_Pain_Analysis.py")],
    active_target="pages/3_Gain_Pain_Analysis.py",
)

# ==========================================
# PART 1 — PROBLEM SELECTION (Friend's)
# ==========================================

st.title("AI Gain-Pain Analysis")
st.caption("Weigh expected gains against implementation pains, NIST AI RMF aligned.")

problems = get_problems()
if not problems:
    st.warning("No problems found. Please submit a problem in Module 1 first.")
    st.stop()

problem_dict = {row[1]: row[0] for row in problems}
problem_options = ["-- Select a Problem --"] + list(problem_dict.keys())
selected_problem = st.selectbox("Select AI Opportunity", problem_options)

if selected_problem == "-- Select a Problem --":
    st.info("Please select a problem to begin analysis.")
    st.stop()

pid = problem_dict[selected_problem]
problem = db_get_problem(pid)

assessments = db_load_assessments(pid)
assessment = assessments[0] if assessments else None

with st.container(border=True):
    st.subheader("Problem Summary")
    st.info(problem.get("problem_statement", ""))
    c1, c2 = st.columns(2)
    with c1:
        st.write("**Business Objective**")
        st.write(problem.get("business_objective", "") or "—")
    with c2:
        if assessment:
            st.write("**M2 Feasibility Verdict**")
            st.write(f"{assessment.get('verdict','—')} · {float(assessment.get('overall_score') or 0):.2f}/5")
        else:
            st.write("**M2 Feasibility Verdict**")
            st.write("Not assessed yet")

if not assessment:
    st.error("No feasibility assessment found for this problem. Please complete "
              "**📊 Feasibility Assessment** first.")
    st.stop()

st.divider()

# ==========================================
# NEW FEATURE — choose clarifying questions vs run directly
# ==========================================

if "m3_result_cache" not in st.session_state:
    st.session_state["m3_result_cache"] = {}
result_cache = st.session_state["m3_result_cache"]

if pid not in result_cache:
    st.markdown("### How would you like to proceed?")
    mode = st.radio(
        "Choose an option",
        ["Ask Clarifying Questions", "Run Gain-Pain Analysis Directly"],
        key=f"m3_mode_{pid}",
        horizontal=True,
        label_visibility="collapsed",
    )

    # ── Option A: Ask Clarifying Questions ──────────────────────────────
    if mode == "Ask Clarifying Questions":
        q_cache = f"m3_smart_q_{pid}"
        ans_cache = f"m3_smart_ans_{pid}"
        st.session_state.setdefault(q_cache, None)
        st.session_state.setdefault(ans_cache, {})

        st.markdown("#### Clarifying Questions (generated by the LLM)")
        col_g, col_h = st.columns(2)
        with col_g:
            selected_teams = st.multiselect(
                "Which teams should be questioned?",
                ["Technical Team", "Marketing Team", "Finance Team",
                 "Legal / Compliance", "HR / Change Mgmt"],
                default=["Technical Team", "Finance Team"],
                key=f"m3_teams_{pid}",
            )
        with col_h:
            q_depth = st.radio("Question depth", ["Standard (3-4 per team)", "Deep Dive (5-6 per team)"],
                                horizontal=True, key=f"m3_depth_{pid}")

        if st.session_state[q_cache] is None:
            if st.button("🤖 Generate clarifying questions", key=f"m3_gen_q_{pid}"):
                if not selected_teams:
                    st.warning("Select at least one team to question.")
                else:
                    with st.spinner("LLM is generating clarifying questions…"):
                        q_result = call_smart_questions_ai(problem, {}, assessment, {}, selected_teams, q_depth)
                    if q_result:
                        st.session_state[q_cache] = q_result
                    else:
                        st.error("Failed to generate questions. Check your AI Settings in the sidebar.")
                    st.rerun()
        else:
            q_result = st.session_state[q_cache]
            st.markdown("##### Generated questions")
            for team_name, team_data in q_result.get("teams", {}).items():
                st.markdown(f"**{team_name}** — {team_data.get('rationale','')}")
                for i, q in enumerate(team_data.get("questions", []), 1):
                    qtext = q.get("question", "")
                    key_ans = f"{ans_cache}_{team_name}_{i}"
                    st.markdown(f"Q{i}. {qtext}")
                    ans = st.text_area("Answer", key=key_ans, height=80, label_visibility="collapsed")
                    if ans:
                        st.session_state[ans_cache][key_ans] = {"q": qtext, "a": ans}

            b1, b2 = st.columns(2)
            with b1:
                if st.button("🔄 Regenerate questions", key=f"m3_regen_{pid}", width='stretch'):
                    st.session_state[q_cache] = None
                    st.session_state[ans_cache] = {}
                    st.rerun()
            with b2:
                if st.button("▶️ Run Gain-Pain Analysis with answers", type="primary",
                              key=f"m3_run_with_ans_{pid}", width='stretch'):
                    answers = [v for v in st.session_state[ans_cache].values() if v.get("a")]
                    with st.spinner("AI is running gain-pain analysis with your answers…"):
                        ai_result = call_m3_ai(problem, assessment, dept_answers=answers)
                    if ai_result:
                        result_cache[pid] = ai_result
                        st.rerun()
                    else:
                        st.error("Analysis failed. Check your AI Settings and try again.")

    # ── Option B: Run Directly — no extra button, runs immediately ─────
    else:
        with st.spinner("AI is running gain-pain analysis…"):
            ai_result = call_m3_ai(problem, assessment, dept_answers=None)
        if ai_result:
            result_cache[pid] = ai_result
            st.rerun()
        else:
            st.error("Analysis failed. Check your AI Settings and try again.")
            st.stop()

    st.stop()

# ==========================================
# PERSIST + RESULTS  (My Project)
# ==========================================

result = result_cache[pid]

existing = db_load_gainpain(pid)
if not existing or json.loads(existing[0].get("ai_analysis") or "{}") != result:
    gains = result.get("gains", {})
    pains = result.get("pains", {})
    rec_id = f"GP-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    db_save_gainpain({
        "id": rec_id, "problem_id": pid, "assessment_id": assessment.get("id", ""),
        "analysed_at": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "business_value_gain": gains.get("business_value_gain", 0),
        "strategic_alignment": gains.get("strategic_alignment", 0),
        "efficiency_gain": gains.get("efficiency_gain", 0),
        "innovation_potential": gains.get("innovation_potential", 0),
        "implementation_cost": pains.get("implementation_cost", 0),
        "operational_risk": pains.get("operational_risk", 0),
        "adoption_resistance": pains.get("adoption_resistance", 0),
        "compliance_burden": pains.get("compliance_burden", 0),
        "avg_gains": result.get("avg_gains", 0),
        "avg_pains": result.get("avg_pains", 0),
        "priority_score": result.get("priority_score", 0),
        "priority_score_scaled": result.get("priority_score_scaled", 0),
        "priority_band": result.get("priority_band", ""),
        "ai_analysis": json.dumps(result),
        "question_mode": st.session_state.get(f"m3_mode_{pid}", ""),
    })
    band = result.get("priority_band", "")
    new_status = {"High Priority": "Approved", "Medium Priority": "Under Review",
                  "Low Priority": "Deferred"}.get(band, "Under Review")
    db_update_status(pid, new_status)

latest = db_load_gainpain(pid)[0]
band = latest["priority_band"]
pb = PRIORITY_BANDS.get(band, PRIORITY_BANDS["Medium Priority"])
scaled = latest["priority_score_scaled"]
gains_data = result.get("gains", {})
pains_data = result.get("pains", {})
gain_reasoning = result.get("gain_reasoning", {})
pain_reasoning = result.get("pain_reasoning", {})

st.success(f"Analysis complete · {latest['analysed_at']} · NIST AI RMF aligned")

st.markdown(f"""
<div style="background:{pb['bg']};border:1.5px solid {pb['color']};border-radius:14px;
            padding:1.2rem 1.6rem;margin-bottom:1.5rem;
            display:flex;justify-content:space-between;align-items:center;">
  <div>
    <div style="font-size:0.7rem;color:{pb['color']};font-weight:700;letter-spacing:0.08em;">
      PRIORITY SCORE {M3_PRIORITY_FORMULA_HTML}
    </div>
    <div style="font-size:1.9rem;font-weight:800;color:{pb['color']};margin-top:2px;">
      {scaled:.1f}<span style="font-size:1rem;opacity:0.6;"> / 10</span>
    </div>
    <div style="font-size:0.73rem;color:{pb['color']};margin-top:4px;opacity:0.85;">
      Avg Gains {M3_AVG_GAINS_FORMULA_HTML} <b>{latest['avg_gains']:.2f}/5</b>
      &nbsp;·&nbsp;
      Avg Pains {M3_AVG_PAINS_FORMULA_HTML} <b>{latest['avg_pains']:.2f}/5</b>
    </div>
  </div>
  <div style="font-size:1rem;font-weight:700;color:{pb['color']};text-align:right;">
    {band}<br>
    <span style="font-size:0.7rem;opacity:0.7;font-weight:400;">
      ≥ 7.0 High &nbsp;·&nbsp; 4.0–6.9 Medium &nbsp;·&nbsp; &lt; 4.0 Low
    </span>
  </div>
</div>""", unsafe_allow_html=True)

col_gain, col_pain = st.columns(2, gap="large")
with col_gain:
    st.markdown("**📈 Gains**")
    for d in GAIN_DIMENSIONS:
        s = gains_data.get(d["id"], 0)
        pct = int(s / 5 * 100)
        col = "#1D9E75" if s >= 3.5 else "#C07A10" if s >= 2.5 else "#C0392B"
        rsn = gain_reasoning.get(d["id"], "")
        basis = M3_SCORING_BASIS.get(d["id"], "")
        st.markdown(f"""
        <div style="margin-bottom:1rem;">
          <div style="display:flex;justify-content:space-between;font-size:0.82rem;margin-bottom:3px;">
            <span>{d['icon']} {d['label']} <span style="color:#aaa;font-size:0.7rem;">{d['nist']}</span></span>
            <span style="font-weight:700;color:{col};">{s:.1f}/5</span>
          </div>
          <div style="background:#F0F0F8;border-radius:6px;height:7px;">
            <div style="background:{col};width:{pct}%;height:7px;border-radius:6px;"></div>
          </div>
          {f'<div style="font-size:0.75rem;color:#444;margin-top:5px;font-style:italic;">📌 {rsn}</div>' if rsn else ""}
          <div class="score-basis">
            <span class="basis-label">Score basis</span>
            {basis}
          </div>
        </div>""", unsafe_allow_html=True)

with col_pain:
    st.markdown("**📉 Pains**")
    for d in PAIN_DIMENSIONS:
        s = pains_data.get(d["id"], 0)
        pct = int(s / 5 * 100)
        col = "#C0392B" if s >= 3.5 else "#C07A10" if s >= 2.5 else "#1D9E75"
        rsn = pain_reasoning.get(d["id"], "")
        basis = M3_SCORING_BASIS.get(d["id"], "")
        st.markdown(f"""
        <div style="margin-bottom:1rem;">
          <div style="display:flex;justify-content:space-between;font-size:0.82rem;margin-bottom:3px;">
            <span>{d['icon']} {d['label']} <span style="color:#aaa;font-size:0.7rem;">{d['nist']}</span></span>
            <span style="font-weight:700;color:{col};">{s:.1f}/5</span>
          </div>
          <div style="background:#F0F0F8;border-radius:6px;height:7px;">
            <div style="background:{col};width:{pct}%;height:7px;border-radius:6px;"></div>
          </div>
          {f'<div style="font-size:0.75rem;color:#444;margin-top:5px;font-style:italic;">📌 {rsn}</div>' if rsn else ""}
          <div class="score-basis">
            <span class="basis-label">Score basis</span>
            {basis}
          </div>
        </div>""", unsafe_allow_html=True)

chart_data = pd.DataFrame({
    "Dimension": [d["label"] for d in GAIN_DIMENSIONS] + [d["label"] for d in PAIN_DIMENSIONS],
    "Score": [gains_data.get(d["id"], 0) for d in GAIN_DIMENSIONS] +
             [pains_data.get(d["id"], 0) for d in PAIN_DIMENSIONS],
})
st.bar_chart(chart_data.set_index("Dimension")["Score"], color="#6C63FF")

quick_wins = result.get("quick_wins", [])
mitigations = result.get("mitigation_actions", [])
next_step = result.get("recommended_next_step", "")

qw_col, mt_col = st.columns(2, gap="medium")
with qw_col:
    if quick_wins:
        st.markdown("**⚡ Quick Wins**")
        for q in quick_wins:
            st.markdown(f"- {q}")
with mt_col:
    if mitigations:
        st.markdown("**🛡️ Pain Mitigations**")
        for m in mitigations:
            st.markdown(f"- {m}")

if next_step:
    st.info(f"**Recommended next step:** {next_step}")

low_conf = result.get("low_confidence_dimensions", [])
teams = result.get("teams_to_consult", [])
consult_r = result.get("consultation_reason", "")
if low_conf or teams:
    st.markdown(f"""
    <div style="background:#FFF8E7;border:1.5px solid #C07A10;border-radius:12px;
                padding:0.9rem 1.2rem;margin-top:0.8rem;">
      <div style="font-size:0.78rem;font-weight:700;color:#C07A10;letter-spacing:0.06em;margin-bottom:4px;">
        🤖 AI RECOMMENDS ADDITIONAL TEAM INPUT
      </div>
      {"<div style='font-size:0.82rem;color:#444;margin-bottom:6px;'>" + consult_r + "</div>" if consult_r else ""}
      {"<div style='font-size:0.8rem;color:#444;'><b>Low-confidence dimensions:</b> " + ", ".join(low_conf) + "</div>" if low_conf else ""}
      {"<div style='font-size:0.8rem;color:#444;'><b>Suggested teams to consult:</b> " + ", ".join(teams) + "</div>" if teams else ""}
    </div>""", unsafe_allow_html=True)

export_row = {
    "Analysis ID": latest["id"], "Problem ID": pid, "Analysed at": latest["analysed_at"],
    "Priority Band": band, "Priority Score": f"{scaled:.1f}/10",
    "Avg Gains": f"{latest['avg_gains']:.2f}", "Avg Pains": f"{latest['avg_pains']:.2f}",
}
for d in GAIN_DIMENSIONS:
    export_row[d["label"]] = gains_data.get(d["id"], 0)
for d in PAIN_DIMENSIONS:
    export_row[d["label"]] = pains_data.get(d["id"], 0)

csv = pd.DataFrame([export_row]).to_csv(index=False).encode("utf-8")
st.download_button("⬇️ Download CSV", csv, f"gainpain_{latest['id']}.csv", "text/csv")

st.divider()

# ==========================================
# NEW FEATURE — Satisfied with Analysis?
# ==========================================

st.markdown("### Satisfied with Analysis?")
sat_col1, sat_col2, sat_col3 = st.columns([1, 1, 3])
with sat_col1:
    if st.button("✅ Yes", width='stretch'):
        st.success("Great — this analysis is ready for Governance Review.")
with sat_col2:
    if st.button("🧑‍⚖️ Request Expert Review", width='stretch'):
        st.session_state["expert_review_problem_id"] = pid
        st.session_state["expert_review_gainpain_id"] = latest["id"]
        st.switch_page("pages/6_Expert_Advice.py")
